# Lab | Data Aggregation and Filtering

In this challenge, we will continue to work with customer data from an insurance company. We will use the dataset called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by first performing data cleaning, formatting, and structuring.

In [39]:
import pandas as pd

In [40]:
url ='https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv'
df = pd.read_csv(url)

In [41]:
df.head()

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN

In [42]:
df.columns = df.columns.str.lower()

In [43]:
df.columns = df.columns.str.replace(" ", "_")

1. Create a new DataFrame that only includes customers who:
   - have a **low total_claim_amount** (e.g., below $1,000),
   - have a response "Yes" to the last marketing campaign.

In [44]:
df['response'].value_counts()

response
No     8813
Yes    1466
Name: count, dtype: int64

In [45]:
df_claim = df[(df['total_claim_amount']>1000) & (df['response']== "Yes")]

2. Using the original Dataframe, analyze:
   - the average `monthly_premium` and/or customer lifetime value by `policy_type` and `gender` for customers who responded "Yes", and
   - compare these insights to `total_claim_amount` patterns, and discuss which segments appear most profitable or low-risk for the company.

In [46]:
yes_responders = df[df["response"]== 'Yes']
yes_responders.head()

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
8,8,FM55990,California,5989.773931,Yes,Premium,College,1/19/11,Employed,M,...,0.0,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Sports Car,Medsize,NaN
15,15,CW49887,California,4626.801093,Yes,Basic,Master,1/16/11,Employed,F,...,0.0,1,Special Auto,Special L1,Offer2,Branch,547.200000,SUV,Medsize,NaN
19,19,NJ54277,California,3746.751625,Yes,Extended,College,2/26/11,Employed,F,...,1.0,1,Personal Auto,Personal L2,Offer2,Call Center,19.575683,Two-Door Car,Large,A
27,27,MQ68407,Oregon,4376.363592,Yes,Premium,Bachelor,2/28/11,Employed,F,...,0.0,1,Personal Auto,Personal L3,Offer2,Agent,60.036683,Four-Door Car,Medsize,NaN

In [51]:
yes_responders.columns

Index(['unnamed:_0', 'customer', 'state', 'customer_lifetime_value',
       'response', 'coverage', 'education', 'effective_to_date',
       'employmentstatus', 'gender', 'income', 'location_code',
       'marital_status', 'monthly_premium_auto', 'months_since_last_claim',
       'months_since_policy_inception', 'number_of_open_complaints',
       'number_of_policies', 'policy_type', 'policy', 'renew_offer_type',
       'sales_channel', 'total_claim_amount', 'vehicle_class', 'vehicle_size',
       'vehicle_type'],
      dtype='object')

In [49]:
grouped = yes_responders.groupby(['policy_type', 'gender'])

In [53]:
comparison = grouped[["monthly_premium_auto", "customer_lifetime_value", "total_claim_amount"]].mean().round(2)
comparison

                       monthly_premium_auto  customer_lifetime_value  \
policy_type    gender
Corporate Auto F                      94.30                  7712.63
               M                      92.19                  7944.47
Personal Auto  F                      99.00                  8339.79
               M                      91.09                  7448.38
Special Auto   F                      92.31                  7691.58
               M                      86.34                  8247.09

                       total_claim_amount
policy_type    gender
Corporate Auto F                   433.74
               M                   408.58
Personal Auto  F                   452.97
               M                   457.01
Special Auto   F                   453.28
               M                   429.53

3. Analyze the total number of customers who have policies in each state, and then filter the results to only include states where there are more than 500 customers.

In [56]:
customers_state = df.groupby("state").size().reset_index(name="customer_count")

In [58]:
customers_over_500 = customers_state[customers_state["customer_count"] > 500]
customers_over_500

        state  customer_count
0     Arizona            1937
1  California            3552
2      Nevada             993
3      Oregon            2909
4  Washington             888

4. Find the maximum, minimum, and median customer lifetime value by education level and gender. Write your conclusions.

In [65]:
customer_lv = df.groupby(["education", "gender"])["customer_lifetime_value"].agg(["max", "min", "median"]).round(0)
customer_lv

                                 max     min  median
education            gender
Bachelor             F       73226.0  1904.0  5641.0
                     M       67907.0  1898.0  5548.0
College              F       61850.0  1899.0  5624.0
                     M       61135.0  1918.0  6006.0
Doctor               F       44856.0  2396.0  5332.0
                     M       32677.0  2268.0  5578.0
High School or Below F       55277.0  2145.0  6040.0
                     M       83325.0  1941.0  6287.0
Master               F       51016.0  2418.0  5730.0
                     M       50568.0  2272.0  5579.0

## Bonus

In [69]:
df.columns

Index(['unnamed:_0', 'customer', 'state', 'customer_lifetime_value',
       'response', 'coverage', 'education', 'effective_to_date',
       'employmentstatus', 'gender', 'income', 'location_code',
       'marital_status', 'monthly_premium_auto', 'months_since_last_claim',
       'months_since_policy_inception', 'number_of_open_complaints',
       'number_of_policies', 'policy_type', 'policy', 'renew_offer_type',
       'sales_channel', 'total_claim_amount', 'vehicle_class', 'vehicle_size',
       'vehicle_type'],
      dtype='object')

5. The marketing team wants to analyze the number of policies sold by state and month. Present the data in a table where the months are arranged as columns and the states are arranged as rows.

In [77]:
df['effective_to_date'] = pd.to_datetime(df['effective_to_date'])
df['month'] = df['effective_to_date'].dt.month_name()

/var/folders/9l/kk5xty3s5gn6t443byvnr8040000gn/T/ipykernel_14611/132705103.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['effective_to_date'] = pd.to_datetime(df['effective_to_date'])

In [ ]:
policies  = df.pivot_table(
    values="customer", 
    index="state",
    columns="month",
    aggfunc="count"
)
policies.T

state     Arizona  California  Nevada  Oregon  Washington
month
February      929        1634     442    1344         425
January      1008        1918     551    1565         463

6.  Display a new DataFrame that contains the number of policies sold by month, by state, for the top 3 states with the highest number of policies sold.

*Hint:*
- *To accomplish this, you will first need to group the data by state and month, then count the number of policies sold for each group. Afterwards, you will need to sort the data by the count of policies sold in descending order.*
- *Next, you will select the top 3 states with the highest number of policies sold.*
- *Finally, you will create a new DataFrame that contains the number of policies sold by month for each of the top 3 states.*

In [81]:
policies_state_month = df.groupby(["month","state"]).size().reset_index(name="policy_count")
policies_state_month

      month       state  policy_count
0  February     Arizona           929
1  February  California          1634
2  February      Nevada           442
3  February      Oregon          1344
4  February  Washington           425
5   January     Arizona          1008
6   January  California          1918
7   January      Nevada           551
8   January      Oregon          1565
9   January  Washington           463

7. The marketing team wants to analyze the effect of different marketing channels on the customer response rate.

Hint: You can use melt to unpivot the data and create a table that shows the customer response rate (those who responded "Yes") by marketing channel.

External Resources for Data Filtering: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

In [ ]:
# your code goes here